name: Deploy AWS CDK

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}

      - name: install npm
        run: 'npm install -g npm'

      - name: Install AWS CDK
        run: 'npm install -g aws-cdk' 

      - name: Install Requirements 
        run: 'pip install -r requirements.txt'
        working-directory: .

      - name: CDK Synth
        run: cdk synth
        working-directory: .
              
      - name: CDK bootstrap
        run: cdk bootstrap
        working-directory: .

      - name: CDK Deploy
        run: cdk deploy --require-approval never
        working-directory: .
        
      # - name: CDK Destroy
      #   run: cdk destroy --force
      #   working-directory: .
